"""Analyze successful calibration runs together with explicit failure artifacts."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from _bootstrap import add_src_to_path

ROOT = add_src_to_path()

from eg_sft.experiment.cloud_v2_analysis import (  # noqa: E402
    TRAINING_PROFILES,
    read_json_object,
)
from eg_sft.experiment.cloud_v2_failure_analysis import (  # noqa: E402
    analyze_training_calibration_with_failures,
)
from eg_sft.training.b500 import file_sha256  # noqa: E402


def _parse_assignments(values: list[str]) -> dict[str, Path]:
    parsed: dict[str, Path] = {}
    for value in values:
        profile, separator, raw_path = value.partition("=")
        if not separator or profile not in TRAINING_PROFILES or not raw_path:
            raise ValueError(f"expected frozen PROFILE=PATH, received {value!r}")
        if profile in parsed:
            raise ValueError(f"duplicate profile assignment: {profile}")
        parsed[profile] = Path(raw_path).resolve()
    return parsed


def _write_json_exclusive(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--run",
        action="append",
        default=[],
        metavar="PROFILE=RUN_DIR",
        help="A completed PASS calibration run; repeat for every successful profile.",
    )
    parser.add_argument(
        "--failure",
        action="append",
        default=[],
        metavar="PROFILE=FAILURE_JSON",
        help="An immutable real failure record; never generated by this analyzer.",
    )
    parser.add_argument(
        "--analysis-config",
        type=Path,
        default=Path("configs/cloud_v2_calibration_analysis_v1.json"),
    )
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    run_paths = _parse_assignments(args.run)
    failure_paths = _parse_assignments(args.failure)
    config_path = args.analysis_config.resolve()
    config = read_json_object(config_path)
    if config.get("analysis_version") != "cloud-v2-calibration-analysis-v1":
        raise ValueError("unexpected cloud-v2 analysis config version")
    report = analyze_training_calibration_with_failures(
        run_paths=run_paths,
        failure_paths=failure_paths,
        thresholds=config["training"],
    )
    report["analysis_config_sha256"] = file_sha256(config_path)
    report["failure_artifact_policy"] = (
        "The analyzer only reads user-supplied immutable failure JSON. It never fabricates "
        "a remote failure artifact or infers missing GPU memory values."
    )
    if args.output is not None:
        _write_json_exclusive(args.output.resolve(), report)
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
